require_relative 'fatboy/cloudformation.rb'
require_relative 'fatboy/context.rb'
require_relative 'fatboy/cosmos.rb'
require_relative 'fatboy/resource_graph.rb'
require_relative 'fatboy/scm_helper.rb'
require_relative 'fatboy/spud.rb'
require_relative 'fatboy/wormhole.rb'

require_relative 'fatboy/resources/lambda_deployment.rb'
require_relative 'fatboy/resources/spud_stack.rb'
